[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["next"]

[functions."___netlify-server-handler"]
  timeout = 60

[[plugins]]
  package = "@netlify/plugin-nextjs"
